### ISSUE TITLE
Question: Menucontroller() error

### ISSUE THREAD

**Issue by dabes** [Santos-Enoque/flutter-web-dashboard-template#1]
I'm trying to follow your guide on skillshare, but i have some error i don't know how to resolve, following your code i was getting a null error so i started to fix it to run without disabling the null-safe mode as you can see on the repo: https://github.com/dabes/starter_flutter . but now i got this error and don't know how to proceed, if you could help me?  
![image](https://user-images.githubusercontent.com/1524583/125705033-51db24f4-8d49-48f9-91e9-ec35a040e4c8.png)

**Comment by Santos-Enoque** [comment]
Hello Daniel, I will have a look at your repo and get back to you

**Comment by dabes** [comment]
Hello Santos, i managed to resolve, on menu_controller.dart on the line 7:

**Comment by Santos-Enoque** [comment]
Hello mate, sorry for getting back to you late, but I am glad you were able to find the error
